spring:
  application:
    name: Callbreak Game Logs
  data:
    mongodb:
      database: CallbreakGameStats
      uri: mongodb://mongoadmin:luciprod-666@10.0.42.73:27017,10.0.41.103:27017,10.0.40.124:27017/admin?replicaSet=rs0
  aws:
    secretmanager:
      secretName: prod/Mongo
      region: ap-south-1 
      
mongo-db:
   connection-pool:
     core: 10
     max: 50
     maxIdleTime: 30000
     timeout: 30000
      
pubsub:
  namespace: 10.0.33.44:9092,10.0.35.180:9093
  topic: callbreak-gamelogs
  group-id: callbreak-gamelogs-prod-event-group
  consumer-count: 4
       
server:
   port: 3177

management:
  endpoint:
    health:
      probes:
        enabled: true
        
consul:
   url: http://10.0.0.183:8500
   path: callbreakGameLogs/
